### ISSUE TITLE
Error: (SSH) Channel open failure: open failed

### ISSUE THREAD

**Issue by mikehchuck** [mikeal/sequest#46]
Hello,

I am working with sequest to download and upload images from a server. I am able to upload pretty much any images, but when I try to upload a ~1Mb png image, it gives me this error:

> { Error: (SSH) Channel open failure: open failed
    at SSH2Stream.onFailure (/Users/michajoy/Documents/git/electron-react-case-cobbler/node_modules/ssh2/lib/client.js:1068:13)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/Users/michajoy/Documents/git/electron-react-case-cobbler/node_modules/ssh2-streams/lib/ssh.js:3423:10)
    at SSH2Stream._transform (/Users/michajoy/Documents/git/electron-react-case-cobbler/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/michajoy/Documents/git/electron-react-case-cobbler/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18) reason: 'ADMINISTRATIVELY_PROHIBITED', lang: '' }

I am able to upload very similar images, but this one gives me this error. Is it because of the file size?

Thanks.

**Comment by mikehchuck** [comment]
It was a strange fix, but I just ended my connection and started a new one at the beginning of the function. It seemed like it somehow ran out of requests or something of that nature? Not quite sure, I have a degree in Physics, not CS ;)
